metadata:
  name: euro-calliope
  title: Euro Calliope for ECEMF
  description: Euro Calliope for ECEMF
  keywords:
    - energy system design
    - europe
    - ecemf
  licenses: [CC0-1.0]

indices: 
  technology: technology.csv
  carriers: carriers.csv
  model: calliope
  scenario: diag-npi
  year: 2030
