name: Publish docs

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  docs:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          apt-get install -y \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            latexmk
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Build docs
        run: |
          make -C doc html
          make -C doc latexpdf
          cp doc/_build/latex/sentinel-data-format.pdf doc/_build/html/
      - name: Publish pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
          force-orphan: true
