name: Publish docs

on:
  push:
    branches:
      - master
    paths:
      - "doc/**"
      - "sark/**"
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  docs:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.head_commit.message, 'skip doc'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            latexmk
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Build docs
        run: |
          wget https://code.orgmode.org/bzg/org-mode/raw/master/contrib/scripts/ditaa.jar -P doc
          java -Dfile.encoding=UTF-8 -jar doc/ditaa.jar doc/ecosystem.txt doc/ecosystem.png
          make -C doc latexpdf html
      - name: Publish pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
          force_orphan: true
