name: Unit tests

on:
  push:
    paths-ignore:
      - "doc/**"
  pull_request:
    paths-ignore:
      - "doc/**"

jobs:
  lint:
    if: "!(contains(github.event.head_commit.message, 'skip ci') || contains(github.event.head_commit.message, 'skip test'))"

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint w/ flake8 - syntax error or undefined names
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint w/ flake8 - all
        continue-on-error: true
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: lint

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-extras.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Test w/ pytest
        run: |
          pytest --cov=friendly_data
      - name: Code coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

  test_wo_optional:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Import optional module & check error
        run: |
          for m in {cli,converters,dpkg,helpers,io,metatools,tseries,validate}; \
          do \
              python -c "from friendly_data import ${m}"; \
          done
          python -c 'from friendly_data import iamc' |& grep -qF "'pyam', use pip"

  test_latest:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: lint

    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # add frictionless back to the list to do version unlimited checks
        req-version: [registry]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (latest ${{ matrix.req-version }})
        run: |
          python -m pip install --upgrade pip
          git apply ./dev/requirements-${{ matrix.req-version }}.patch
          pip install -r requirements.txt
          pip install -r requirements-extras.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Test w/ pytest
        run: |
          pytest

  style:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black toml
      - name: Format source w/ black
        # fail when file(s) would be formatted
        run: black --check .

  type-hints:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        continue-on-error: true
        # b/c mypy returns non-zero code, and the step fails
        run: |
          python -m pip install --upgrade pip
          pip install mypy{,_extensions}
          echo y | mypy --install-types
      - name: Type check w/ mypy
        run: mypy --check-untyped-defs --pretty
